###List all messages
GET http://localhost:3001/messages

###Create a new message
POST http://localhost:3001/messages
content-type: application/json

{
  "content": "0905519435"
}

###Get a particular message
GET http://localhost:3001/messages/0905519435 